driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/ansible-dk']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - omnibus::default                     # Installs omnibus and the build toolchain
      - ansible-dk-builder::default          # Executes the build
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/ansible-dk
